# Generated by Django 3.0.5 on 2021-07-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_agent_chat_client_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='client',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UsersActivityLog',
        ),
        migrations.DeleteModel(
            name='UsersRole',
        ),
        migrations.DeleteModel(
            name='UsersStatus',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
